"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Jonas Keller"
email = "jonas.r.keller@gmail.com"

[ui]
editor = "vim"
default-command = "log"
diff-editor = ":builtin"
